### ISSUE TITLE
Multichannel output expansion

### ISSUE THREAD

**Issue by 100303602** [rodrigodzf/Jack-Audio-For-Unity#1]
I wanted to know if your plugin allows to take a Unity game with 3D audio sources and to distribute their sound across an arbitrary number of speakers (say, 10 speakers) to create an immersive net of speakers (which would be located at your right, left, above you, below you...).

**Comment by rodrigodzf** [comment]
yes. It routes the output of an AudioSource to a Jack channel. You can then route each Jack channel to a particular output of your audio card
