### ISSUE TITLE
Receive jack signal at AudioSource and send audio via Jack Unity Mixer plugin

### ISSUE THREAD

**Issue by Schroedingers-Cat** [rodrigodzf/Jack-Audio-For-Unity#10]
I'm trying to receive an audio signal from Jack and feed that into an AudioSource with the JackSourceReceive-Script. This part works perfectly. However, instead of sending with the JackSourceSend-Script, I want to send the audio with the plugin from Unitys mixing window to an external DAW. 
The DAW however either receives no signal (if the "Use Effect" bool is set to false) or receives garbage (if the "Use Effect" bool is set to true). Is receiving with the JackSourceSend-Script and sending with the mixer plugin possible?

**Comment by rodrigodzf** [comment]
Hi,
Sorry for the 2 years delay. It is not possible with the current plugin. I will try to modify it for this case

**Comment by rodrigodzf** [comment]
Hi,
This issue should be solved in the `dev` branch (concretely in 21273769e9f9139be43ba3bdfe73c6020313d542). I did a complete refactor of the library, it should run more stable as well. It is tested with the latest version of unity and under ubuntu18.04.

**Comment by tschindl** [comment]
> I'm trying to receive an audio signal from Jack and feed that into an AudioSource with the JackSourceReceive-Script. This part works perfectly. However, instead of sending with the JackSourceSend-Script, I want to send the audio with the plugin from Unitys mixing window to an external DAW.
> The DAW however either receives no signal (if the "Use Effect" bool is set to false) or receives garbage (if the "Use Effect" bool is set to true). Is receiving with the JackSourceSend-Script and sending with the mixer plugin possible?



> I'm trying to receive an audio signal from Jack and feed that into an AudioSource with the JackSourceReceive-Script. This part works perfectly. However, instead of sending with the JackSourceSend-Script, I want to send the audio with the plugin from Unitys mixing window to an external DAW.
> The DAW however either receives no signal (if the "Use Effect" bool is set to false) or receives garbage (if the "Use Effect" bool is set to true). Is receiving with the JackSourceSend-Script and sending with the mixer plugin possible?

Hey @Schroedingers-Cat  - maybe you can help me, how to get the plugin running. I always get dllnotfound error (AudioJackPlugin) when I try to connect to the jack server. Actually I want to receive audio signals from jack in unity
