### ISSUE TITLE
JackAudio not working on Linux

### ISSUE THREAD

**Issue by francescoandreussi** [rodrigodzf/Jack-Audio-For-Unity#14]
I am using JackAudio for having 3D sound signals in ambisonics format in order to have proper  spatial 3D audio in a 8-speakers configuration.
Trying to use this tool as an "interface" between Unity and the following steps of the audio pipeline, I noticed that it is trying to import a DLL library, but it cannot be done in Linux; hence, I am not able to use the plugin for my purposes. Is it planned to make this plugin compatible with Linux/macOS?

**Comment by modern-online** [comment]
Hi, @francescoandreussi 

Did you manage to get it to work somehow? I'm currently facing the same issue of not being able to compile this for Linux

**Comment by rodrigodzf** [comment]
hi, 
sorry, for the delay but the `dev` branch works with linux (I just tested ubuntu18.04 but should work with others as well). Just use `cmake` and copy the `libUnityJackAudio.so`
