### ISSUE TITLE
Multiple compiler errors on build

### ISSUE THREAD

**Issue by tkoterwas** [rodrigodzf/Jack-Audio-For-Unity#26]
I've imported the package via the package manager and am using JackSend as an audio filter component on a GameObject with an AudioSource. Works perfectly when I play the game in Unity Editor. When I try to build it, the build fails with the following errors:

`Library/PackageCache/com.rodrigodzf.jackaudioforunity@1.1.0/Runtime/JackSendEffectGUI.cs(7,34): error CS0246: The type or namespace name 'IAudioEffectPluginGUI' could not be found (are you missing a using directive or an assembly reference?)
Library/PackageCache/com.rodrigodzf.jackaudioforunity@1.1.0/Runtime/JackSendEffectGUI.cs(27,29): error CS0246: The type or namespace name 'IAudioEffectPlugin' could not be found (are you missing a using directive or an assembly reference?)
Library/PackageCache/com.rodrigodzf.jackaudioforunity@1.1.0/Runtime/JackSendEffectGUI.cs(52,32): error CS0246: The type or namespace name 'IAudioEffectPlugin' could not be found (are you missing a using directive or an assembly reference?)
Library/PackageCache/com.rodrigodzf.jackaudioforunity@1.1.0/Runtime/JackSendEffectGUI.cs(9,28): error CS0115: 'JackSendEffectGUI.Name': no suitable method found to override
Library/PackageCache/com.rodrigodzf.jackaudioforunity@1.1.0/Runtime/JackSendEffectGUI.cs(14,28): error CS0115: 'JackSendEffectGUI.Description': no suitable method found to override
Library/PackageCache/com.rodrigodzf.jackaudioforunity@1.1.0/Runtime/JackSendEffectGUI.cs(19,28): error CS0115: 'JackSendEffectGUI.Vendor': no suitable method found to override
*** Tundra build failed (2.43 seconds), 155 items updated, 161 evaluated
Library/PackageCache/com.rodrigodzf.jackaudioforunity@1.1.0/Runtime/JackSendEffectGUI.cs(7,34): error CS0246: The type or namespace name 'IAudioEffectPluginGUI' could not be found (are you missing a using directive or an assembly reference?)
Library/PackageCache/com.rodrigodzf.jackaudioforunity@1.1.0/Runtime/JackSendEffectGUI.cs(27,29): error CS0246: The type or namespace name 'IAudioEffectPlugin' could not be found (are you missing a using directive or an assembly reference?)
Library/PackageCache/com.rodrigodzf.jackaudioforunity@1.1.0/Runtime/JackSendEffectGUI.cs(52,32): error CS0246: The type or namespace name 'IAudioEffectPlugin' could not be found (are you missing a using directive or an assembly reference?)
Library/PackageCache/com.rodrigodzf.jackaudioforunity@1.1.0/Runtime/JackSendEffectGUI.cs(9,28): error CS0115: 'JackSendEffectGUI.Name': no suitable method found to override
Library/PackageCache/com.rodrigodzf.jackaudioforunity@1.1.0/Runtime/JackSendEffectGUI.cs(14,28): error CS0115: 'JackSendEffectGUI.Description': no suitable method found to override
Library/PackageCache/com.rodrigodzf.jackaudioforunity@1.1.0/Runtime/JackSendEffectGUI.cs(19,28): error CS0115: 'JackSendEffectGUI.Vendor': no suitable method found to override
`

If I try to build the plugin from source as per the ReadMe. I get the following:

`CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find JACK (missing: JACK_LIBRARY JACK_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake-modules/FindJACK.cmake:56 (find_package_handle_standard_args)
  CMakeLists.txt:12 (find_package)
`

Ubuntu 22.04.2 LTS
Unity 2021.3.20f1

Any help or advice would be greatly appreciated. Thanks so much.

**Comment by rodrigodzf** [comment]
This should be solved now. With that said, if you want to use this plugin on a built version you will need to manually initialize the connection to Jack, as in:

```c#
JackLogger.Initialize();
if (JackWrapper.CreateClient((uint)bufferSize, (uint)config.sampleRate))
{
    JackWrapper.RegisterPorts((uint)inputs, (uint)outputs);
    activated = JackWrapper.ActivateClient();
}
```

you can see the initialization process here:

https://github.com/rodrigodzf/Jack-Audio-For-Unity/blob/bb26d5b29072b15b2a3b9b8779f9baa0a9acfb53/Packages/com.rodrigodzf.jackaudio/Editor/JackEditorWIndow.cs#L59-L80

**Comment by tkoterwas** [comment]
Amazing! Thanks for fixing this so quickly! I've just built my project with the updated package files and it works flawlessly. I made a little initialisation script that also uses jack_connect to connect everything up (Im building a sound installation with 24 channels):

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System.Diagnostics;
using System.Threading.Tasks;
using JackAudio;

public class ConfigureJack
{
    [RuntimeInitializeOnLoadMethod]
    static void RuntimeInitializeOnLoad() {
        int outputs = 24;
        int inputs = 0;
    
        int numbuffers;
        int bufferSize;
        bool activated = false;

        AudioSettings.GetDSPBufferSize(out bufferSize, out numbuffers);
        AudioConfiguration config = AudioSettings.GetConfiguration();

        JackLogger.Initialize();
        if (JackWrapper.CreateClient((uint)bufferSize, (uint)config.sampleRate))
        {
            JackWrapper.RegisterPorts((uint)inputs, (uint)outputs);
            activated = JackWrapper.ActivateClient();
        }
        Task.Delay(2000).ContinueWith(t=>ConnectToSystem());
        
    }
    static void ConnectToSystem() {
        string strCmdText;
        strCmdText = "-c 'for i in {0..23}; do jack_connect Unity3D:out\"${i}\" system:playback_$(($i+1)); done;'";
        ProcessStartInfo startInfo = new ProcessStartInfo() {
            FileName = "/bin/bash",
            UseShellExecute = false,
            CreateNoWindow = false,
            Arguments = strCmdText,
        };
        Process proc = new Process() {StartInfo = startInfo };
        proc.Start();
        proc.WaitForExit();
    }
}
```

**Comment by rodrigodzf** [comment]
Cool! Good luck with the installation:)
