### ISSUE TITLE
Commit meta-files and text-serialized untiy assets

### ISSUE THREAD

**Issue by Schroedingers-Cat** [rodrigodzf/Jack-Audio-For-Unity#4]
With #3 merged, all the missing the meta-files of the unity sample project as well as the text-serialized asset files (just open and resave all scenes) should be committed, so the sample project works out of the box when cloning this repository.

**Comment by Schroedingers-Cat** [comment]
@rodrigodzf could you commit the missing meta-files of the unity project demonstrating the use of this jack plugin?

**Comment by rodrigodzf** [comment]
yes ill do it on the weekend, quite busy over here right now
