### ISSUE TITLE
Unity crashes when using more than 40 channels

### ISSUE THREAD

**Issue by Schroedingers-Cat** [rodrigodzf/Jack-Audio-For-Unity#7]
When setting the jack multiplexer to use more than 40 output channels, Unity crashes upon starting the scene. Any idea, why?

**Comment by rodrigodzf** [comment]
not really, it can be that jack cannot handle that many outs, ill check it out on the weekend

**Comment by Schroedingers-Cat** [comment]
I'm using Jack in a different setup with 588 outs in three different software clients in Linux. Will test the windows version soon.

**Comment by Schroedingers-Cat** [comment]
Were you able to reproduce this? I don't have a mac to test, but it is happening on different Windows 10 installation with Unity 5.6.-2017.1.

**Comment by Schroedingers-Cat** [comment]
Any news on this?

**Comment by rodrigodzf** [comment]
I could not reproduce this error on OSX. I’m using 50 out channels and seems to be working fine. Does it work with 40 with your setup though? I will upload a new scene to test this.

**Comment by Schroedingers-Cat** [comment]
Alright, thank you for looking into this! Your test scene works flawlessly.

However, I'm talking about the audio mixer plugin. Therefore, I need to set the Jack Multiplexer script to 42 outputs and active `Use Effects`. I pushed the modified `TestSendEffect.unity` scene to branch `debug/crash-42-fx-outs`, commit f5b94e726ad4579d551b5dc7c7e363665624600a. Starting that scene with the aforementioned setting crashes Unity instantly.
My setup is:
* Unity 5.6.1f1
* Windows 10 64 bit
* Jack 1.9.11

The crashlog points to an access violation in AudioPluginDemo.dll.

Does the modified scene work on OSX?

**Comment by rodrigodzf** [comment]
Ok, I could reproduce the error, but now it should work with an arbitrary amount of channels. Could you recompile for windows and test? I have only OSX at the moment.

**Comment by Schroedingers-Cat** [comment]
That fixed it - thanks a lot! PR for windows build is up. https://github.com/rodrigodzf/Jack-Audio-For-Unity/pull/9
