### ISSUE TITLE
Audio is being transmitted with a gain boost

### ISSUE THREAD

**Issue by Schroedingers-Cat** [rodrigodzf/Jack-Audio-For-Unity#8]
With the standard setup from this repo, the jack plugin seems to add roughly 6dB gain boost to the signals fed to Jack.

To reproduce:
1. Load the scene "TestSendEffect.unity"
2. Set up jack to route Unitys signals to any DAW supporting JackRoute, f.e. Reaper
3. In Reaper, set the audio device to "JackRoute", create four tracks record armed on audio mono input channel 1-4
4. In Unity, press play. Now all four AudioSources can be monitored in Reaper's mixer. I'll focus just on the second track using the file "horse.ogg" so I mute the other tracks in Unity.
5. In Reaper, drag and drop the file "horse.ogg" onto a new track. Play the project in loop mode, so that the file "horse.ogg" gets played back continuously.
6. Now check with an external tool. I'm using DigiCheck from my RME Fireface 802. I mute Reapers audio and disable the Jack Send effect to measure the level at which Unity plays back the horse file. The screenshot shows it's at -2dBfs.
![grafik](https://user-images.githubusercontent.com/6382400/30521848-dc27c504-9bc6-11e7-9c19-210f98f7cb02.png)
7. Now check if Reaper plays back the audio at the same volume. So in Unity, enable the Jack Send plugin and set its volume to 0, which essentially disables Unity's output to the system audio. Now back to Reaper and make sure, only the horse.ogg file plays back. The levels in Reaper's mixer and the external tool should match and it should look like this:  
![grafik](https://user-images.githubusercontent.com/6382400/30522039-0c447b6c-9bca-11e7-9f20-510e58312fa9.png)
8. Now disable the playback of the horse.ogg file in Reaper and unmute the incoming signal from Jack on track 2. If the jack plugin works correct, it should be the same. However, we get a lot of clipping:  
![grafik](https://user-images.githubusercontent.com/6382400/30521924-3aa7a2ba-9bc8-11e7-9c6c-54867605c2fe.png)
9. In Unity, adjust the "Attenuation" to "-5.8". Checking the levels in both, Reaper and RME Digicheck shows that the levels now match:  
![grafik](https://user-images.githubusercontent.com/6382400/30521943-a36cfb06-9bc8-11e7-8e2d-ed891cd8595d.png)

You can also hear and monitor the clipping when connecting Unity to the system audio within Jack directly:  
![grafik](https://user-images.githubusercontent.com/6382400/30522082-a5ca74da-9bca-11e7-812f-7314ae99bd35.png)
So when using the jack plugin in Unity, the level of the signal increases by roughly 6dB. What could that be? Something going on with the conversion from Unity's stereo channels to jack's mono channels?

**Comment by Schroedingers-Cat** [comment]
I redid the entire test scenario, however I set Unity via `Project Settings -> Audio -> Default Speaker Mode` to `Mono`. 
With this setting, the gain boost is exactly 3dB instead of 6dB with stereo at the point the signal is fed into Jack.

**Comment by rodrigodzf** [comment]
The plugin works only with mono now, the down mixing of stereo to mono should be managed outside this plugin. The buffer coming from unity is passed unaltered to Jack, so any down mixing or alteration happens internally in FMOD/Unity.
